name: 'Maximize build disk space'
description: 'Maximize the available disk space for your build job'
branding:
  icon: 'crop'
  color: 'orange'
inputs:
  root-reserve-mb:
    description: 'Space to be left free on the root filesystem, in Megabytes.'
    required: false
    default: 1024
  swap-size-mb:
    description: 'Swap space to create, in Megabytes.'
    required: false
    default: 4096
  build-mount-path:
    description: 'Absolute path to the mount point where the build space will be available, defaults to $GITHUB_WORKSPACE if unset.'
    required: false
  pv-loop-path:
    description: 'Absolute file path for the LVM image created on the root filesystem, the default is usually fine.'
    required: false
    default: '/pv.img'
  remove-dotnet:
    description: 'Removes .NET runtime and libraries. (frees ~17 GB)'
    required: false
    default: 'false'
  remove-android:
    description: 'Removes Android SDKs and Tools. (frees ~11 GB)'
    required: false
    default: 'false'
  remove-haskell:
    description: 'Removes GHC (Haskell) artifacts. (frees ~2.7 GB)'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: |
        echo "Memory and swap:"
        free
        echo
        swapon --show
        echo

        echo "Available storage:"
        df -h
        echo

    - name: Maximize build disk space
      shell: bash
      run: |
          set -euo pipefail
          set -x

          BUILD_MOUNT_PATH="${{ inputs.build-mount-path }}"
          if [[ -z "${BUILD_MOUNT_PATH}" ]]; then
            BUILD_MOUNT_PATH="${GITHUB_WORKSPACE}"
          fi

          echo "Arguments:"
          echo
          echo "  Root reserve: ${{ inputs.root-reserve-mb }} MiB"
          echo "  Swap space:   ${{ inputs.swap-size-mb }} MiB"
          echo "  Mount path:   ${BUILD_MOUNT_PATH}"
          echo "  PV loop path: ${{ inputs.pv-loop-path }}"
          echo -n "  Removing:     "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            echo -n "dotnet "
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            echo -n "android "
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            echo -n "haskell "
          fi
          echo
          echo

          echo "Removing unwanted software... "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            sudo rm -rf /usr/share/dotnet
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            sudo rm -rf /usr/local/lib/android
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            sudo rm -rf /opt/ghc
          fi
          echo "... done"

          TMP_DEV=$(df --output=source  /mnt/ | tail -1)
          ROOT_RESERVE_KB=$(expr ${{ inputs.root-reserve-mb }} \* 1024)
          ROOT_FREE_KB=$(df --block-size=1024 --output=avail / | tail -1)
          ROOT_LVM_SIZE_KB=$(expr $ROOT_FREE_KB - $ROOT_RESERVE_KB)
          ROOT_LVM_SIZE_BYTES=$(expr $ROOT_LVM_SIZE_KB \* 1024)
          VG_NAME=buildvg

          # github runners have an active swap file in /mnt/swapfile
          # we want to reuse the temp disk, so first unmount swap and temp disk
          echo "Unmounting swap and temp disk."
          sudo swapoff -a
          sudo umount /mnt

          echo "Creating LVM Volume."
          # create loop pv image on root fs
          sudo fallocate -l "${ROOT_LVM_SIZE_BYTES}" "${{ inputs.pv-loop-path }}"
          export ROOT_LOOP_DEV=$(sudo losetup --find --show "${{ inputs.pv-loop-path }}")
          sudo pvcreate -f "${ROOT_LOOP_DEV}"

          # create pv on temp disk
          sudo pvcreate -f "${TMP_DEV}"

          # create volume group from these pvs
          sudo vgcreate "${VG_NAME}" "${TMP_DEV}" "${ROOT_LOOP_DEV}"

          echo "Recreating swap"
          # create and activate swap
          sudo lvcreate -L "${{ inputs.swap-size-mb }}M" -n swap "${VG_NAME}"
          sudo mkswap "/dev/mapper/${VG_NAME}-swap"
          sudo swapon "/dev/mapper/${VG_NAME}-swap"

          echo "Creating build volume"
          # create and mount build volume
          sudo lvcreate -l 100%FREE -n buildlv "${VG_NAME}"
          sudo mkfs.ext4 -m0 "/dev/mapper/${VG_NAME}-buildlv"
          sudo mount "/dev/mapper/${VG_NAME}-buildlv" "${BUILD_MOUNT_PATH}"
          sudo chown -R runner "${BUILD_MOUNT_PATH}"

    - name: Disk space report after modification
      shell: bash
      run: |
        echo "Memory and swap:"
        free
        echo
        swapon --show
        echo

        echo "Available storage:"
        df -h
